import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";

import "./globals.css";
import { QueryProvider } from "./query-provider";
import Providers from "./session-provider";
import { getServerSession } from "next-auth";
import authOptions from "@/lib/auth";
import { Toaster } from "sonner";

const inter = Inter_Tight({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${inter.variable}  antialiased`}>
        <QueryProvider>
          <Toaster richColors={true} />
          <Providers session={session}>{children}</Providers>
        </QueryProvider>
      </body>
    </html>
  );
}
